<?php

/**
 * @file
 * Ding Nodes Image Slideshow module functionality.
 */

include_once 'ding_nis.features.inc';

/**
 * Implements hook_post_features_revert().
 */
function ding_nis_post_features_revert($component) {
  _ding_nis_alter_image_fields();
}

/**
 * Handler for altering title image fields.
 */
function _ding_nis_alter_image_fields() {
  $subjects = array(
    'ding_news' => 'field_ding_news_title_image',
    'ding_event' => 'field_ding_event_title_image',
    'ding_page' => 'field_ding_page_title_image',
  );

  foreach ($subjects as $ct => $field) {
    // Loading current field field_instance.
    $instance = field_read_instance('node', $field, $ct);

    // Page CT uses another image style, so setting needed style.
    $image_style = ($ct == 'ding_page') ? 'ding_nodes_image_gallery' : 'ding_nis_secondary_large';

    // Loading field display settings for default view.
    $display_settings = array(
      'label' => 'hidden',
      'type' => 'slideshow',
      'weight' => '12',
      'module' => 'field_slideshow',
      'settings' => array(
        'slideshow_image_style' => $image_style,
        'slideshow_link' => 'colorbox',
        'slideshow_caption' => 'title',
        'slideshow_caption_link' => '',
        'slideshow_fx' => 'slideX',
        'slideshow_speed' => '0',
        'slideshow_timeout' => '0',
        'slideshow_order' => '',
        'slideshow_controls' => 1,
        'slideshow_controls_pause' => 0,
        'slideshow_controls_position' => 'before',
        'slideshow_pause' => 0,
        'slideshow_start_on_hover' => 0,
        'slideshow_pager' => '',
        'slideshow_pager_position' => 'after',
        'slideshow_pager_image_style' => '',
        'slideshow_carousel_image_style' => '',
        'slideshow_carousel_visible' => '3',
        'slideshow_carousel_scroll' => '1',
        'slideshow_carousel_speed' => '500',
        'slideshow_carousel_skin' => '',
        'slideshow_carousel_follow' => 0,
        'slideshow_carousel_vertical' => 0,
        'slideshow_carousel_circular' => 0,
        'slideshow_colorbox_image_style' => 'ding_primary_large',
        'slideshow_colorbox_slideshow' => '',
        'slideshow_colorbox_slideshow_speed' => '4000',
        'slideshow_colorbox_transition' => 'elastic',
        'slideshow_colorbox_speed' => '350',
        'slideshow_field_collection_image' => '',
      ),
    );

    $instance['display']['default'] = $display_settings;
    $instance['widget']['weight'] = 1;

    // Updating field instance.
    field_update_instance($instance);

    // Getting field base settings.
    $base = field_read_field($field);
    // Check if cardinality is correctly set.
    if($base['cardinality'] != '-1') {
      // Force cardinality to -1.
      $base['cardinality'] = '-1';
      // Update field base with unlimited cardinality.
      field_update_field($base);
    }
  }

  variable_set('ding_nis_random', rand());
}
