<?php

/**
 * @file
 * Ding Nodes Image Slideshow module functionality.
 */

include_once 'ding_nis.features.inc';

/**
 * Implements hook_menu().
 */
function ding_nis_menu() {
  $items['admin/config/media/ding_nis'] = [
    'title' => 'Title image display mode',
    'description' => 'Configure display mode for title image.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ding_nis_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'ding_nis.admin.inc',
  ];

  return $items;
}

/**
 * Implements hook_post_features_revert().
 */
function ding_nis_post_features_revert($component) {
  _ding_nis_alter_image_fields();
}

/**
 * Handler for altering title image fields.
 */
function _ding_nis_alter_image_fields() {
  $subjects = array(
    'ding_news' => 'field_ding_news_title_image',
    'ding_event' => 'field_ding_event_title_image',
  );

  foreach ($subjects as $ct => $field) {
    // Loading current field field_instance.
    $instance = field_read_instance('node', $field, $ct);

    // Loading field display settings for default view.
    $display_settings = array(
      'label' => 'hidden',
      'type' => 'slideshow',
      'weight' => '12',
      'module' => 'field_slideshow',
      'settings' => array(
        'slideshow_image_style' => 'ding_nis_secondary_large',
        'slideshow_link' => 'colorbox',
        'slideshow_caption' => 'title',
        'slideshow_caption_link' => '',
        'slideshow_fx' => 'slideX',
        'slideshow_speed' => '0',
        'slideshow_timeout' => '0',
        'slideshow_order' => '',
        'slideshow_controls' => 1,
        'slideshow_controls_pause' => 0,
        'slideshow_controls_position' => 'before',
        'slideshow_pause' => 0,
        'slideshow_start_on_hover' => 0,
        'slideshow_pager' => '',
        'slideshow_pager_position' => 'after',
        'slideshow_pager_image_style' => '',
        'slideshow_carousel_image_style' => '',
        'slideshow_carousel_visible' => '3',
        'slideshow_carousel_scroll' => '1',
        'slideshow_carousel_speed' => '500',
        'slideshow_carousel_skin' => '',
        'slideshow_carousel_follow' => 0,
        'slideshow_carousel_vertical' => 0,
        'slideshow_carousel_circular' => 0,
        'slideshow_colorbox_image_style' => 'ding_primary_large',
        'slideshow_colorbox_slideshow' => '',
        'slideshow_colorbox_slideshow_speed' => '4000',
        'slideshow_colorbox_transition' => 'elastic',
        'slideshow_colorbox_speed' => '350',
        'slideshow_field_collection_image' => '',
      ),
    );

    $instance['display']['default'] = $display_settings;
    $instance['widget']['weight'] = 1;

    // Updating field instance.
    field_update_instance($instance);

    // Getting field base settings.
    $base = field_read_field($field);
    // Check if cardinality is correctly set.
    if ($base['cardinality'] != '-1') {
      // Force cardinality to -1.
      $base['cardinality'] = '-1';
      // Update field base with unlimited cardinality.
      field_update_field($base);
    }
  }

  variable_set('ding_nis_random', rand());
}

/**
 * Implements hook_form_alter().
 */
function ding_nis_form_alter(&$form, &$form_state, $form_id) {
  $content_types = ['ding_event', 'ding_news'];
  foreach ($content_types as $content_type) {
    if ($form_id == $content_type . '_node_form') {
      $group = "group_{$content_type}_images";
      array_push($form['#groups'][$group]->children, 'field_title_image_display_mode');
      $form['#group_children']['field_title_image_display_mode'] = $group;
      $form['field_title_image_display_mode']['#weight'] = 0;

      if (!isset($form['field_title_image_display_mode'][LANGUAGE_NONE]['#default_value'])) {
        $default_mode = variable_get('ding_nis_display_mode', 1);
        $form['field_title_image_display_mode'][LANGUAGE_NONE]['#default_value'] = $default_mode;
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ding_nis_preprocess_field(&$variables) {
  $element = $variables['element'];
  if ($element["#field_name"] == 'field_ding_event_title_image' || $element['#field_name'] == 'field_ding_news_title_image') {
    $display_mode = variable_get('ding_nis_display_mode', 1);
    $entity = $variables['element']['#object'];

    if (isset($entity->field_title_image_display_mode[LANGUAGE_NONE])) {
      $display_mode = $entity->field_title_image_display_mode[LANGUAGE_NONE][0]['value'];
    }

    if ($display_mode == '0') {
      $theme = 'image_formatter';

      $items = [];

      foreach ($variables['element']['#items'] as $item) {
        $items[] = [
          '#theme' => $theme,
          '#item' => $item,
          '#image_style' => 'ding_nis_secondary_large',
        ];
      }

      $variables['items'] = $items;
    }
  }
}

